// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:2e4cda0f-e35a-40c1-862e-1304e3ee809e",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_2C75VeBM9",
    "aws_user_pools_web_client_id": "41c40u7asgft8102uvkajvg7sp",
    "aws_bots": "enable",
    "aws_bots_config": [
        {
            "name": "BookTrip",
            "alias": "$LATEST",
            "region": "us-east-1"
        }
    ]
};


export default awsmobile;
